#spring.application.name=boot_eclipse


spring:
  application:
    name: boot_eclipse
  datasource:
    url: jdbc:mysql://localhost:3306/pojo?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.kunggea.demo.pojo  # 确保与实际包路径一致
  configuration:
    map-underscore-to-camel-case: true
